"""Drafts the `explanation_letter` evidence object (SPEC.md §2 - the LLM's
other allowed job, and SPEC.md §3's `explanation_letter` evidence type).
Degrades to a deterministic template on repeated LLM failure (SPEC.md §7
failure path 2). Takes only the dispute's order-context fields and the
already-normalised communication log - never decides contest/accept
(`policy/` already decided that before this is ever called), never computes
money beyond quoting the given `amount`.

Every return from this module is a `DraftedLetter` carrying its own
`provenance`, assigned on the branch that built it: the validated-model
branch is the only one that produces `LetterProvenance.MODEL`, and only that
value can ever be submitted (`disputedesk/evidence/letter.py`). There is no
longer a separate `human_review_required` boolean travelling beside the
letter - review is implied by `provenance is not MODEL`, so the two cannot
disagree.
"""

from disputedesk.evidence.context import DisputeContext
from disputedesk.evidence.letter import (
    LETTER_MIN_CHARS,
    NETWORK_SUMMARY_MAX_CHARS,
    DraftedLetter,
    LetterProvenance,
    fallback_text_and_provenance,
)
from disputedesk.evidence.llm import LLMClient
from disputedesk.evidence.prompts import load_prompt
from disputedesk.evidence.schemas import ExplanationLetterOutput, NormalizedCommunicationLog
from disputedesk.evidence.validated_call import call_llm_and_validate

PROMPT_VERSION = "explanation_letter_v2"
"""v2 (2026-09-02) states the card network's character limit in the prompt
itself; v1 quoted a 4,000-character budget the wire format could not carry.
Kept as a new versioned file rather than an edit in place, per
`disputedesk/evidence/prompts.py`."""


def _deterministic_fallback(
    context: DisputeContext, evidence_types: tuple[str, ...]
) -> DraftedLetter:
    """No LLM call. States only the raw order-context facts, with no
    narrative framing - a person reviews and improves it later, which the
    returned letter's non-`MODEL` provenance is what actually enforces.
    """
    sentences = [
        f"This letter responds to a chargeback filed under reason code {context.reason_code} "
        f"for a transaction of INR {context.amount:.2f}.",
        f"Address Verification Service match: {'yes' if context.avs_match else 'no'}.",
        f"Card Verification Value match: {'yes' if context.cvv_match else 'no'}.",
        "Device recognized from this customer's prior activity: "
        f"{'yes' if context.device_fingerprint_known else 'no'}.",
        f"Delivery or fulfillment of this transaction: "
        f"{'confirmed' if context.delivery_confirmed else 'not confirmed'}.",
        f"This customer has {context.prior_order_count} prior order(s) on this account.",
        "This letter was generated by a deterministic template because "
        "automated drafting was unavailable; it has not been reviewed by a person yet.",
    ]
    text, provenance = fallback_text_and_provenance(" ".join(sentences))
    return DraftedLetter(
        letter_text=text,
        cites_evidence_types=tuple(evidence_types),
        provenance=provenance,
    )


def draft_explanation_letter(
    context: DisputeContext,
    evidence_types: tuple[str, ...],
    normalized_comms: NormalizedCommunicationLog,
    llm_client: LLMClient,
) -> DraftedLetter:
    prompt = load_prompt(PROMPT_VERSION).format(
        reason_code=context.reason_code,
        amount=f"{context.amount:.2f}",
        avs_match=context.avs_match,
        cvv_match=context.cvv_match,
        device_fingerprint_known=context.device_fingerprint_known,
        delivery_confirmed=context.delivery_confirmed,
        prior_order_count=context.prior_order_count,
        evidence_types=", ".join(evidence_types),
        comms_summary=normalized_comms.summary,
        comms_tone=normalized_comms.tone,
        min_chars=LETTER_MIN_CHARS,
        max_chars=NETWORK_SUMMARY_MAX_CHARS,
    )
    parsed = call_llm_and_validate(llm_client, prompt, ExplanationLetterOutput)
    if parsed is not None:
        # The only construction site of a submittable letter in this codebase.
        # `parsed` is the model's own output, already validated against
        # `ExplanationLetterOutput` - including the network length limit, so
        # nothing is shortened here or anywhere downstream.
        return DraftedLetter(
            letter_text=parsed.letter_text,
            cites_evidence_types=tuple(parsed.cites_evidence_types),
            provenance=LetterProvenance.MODEL,
        )

    return _deterministic_fallback(context, evidence_types)
