"""Drafts the `explanation_letter` evidence object (SPEC.md §2 - the LLM's
other allowed job, and SPEC.md §3's `explanation_letter` evidence type).
Degrades to a deterministic template on repeated LLM failure (SPEC.md §7
failure path 2). Takes only the dispute's order-context fields and the
already-normalised communication log - never decides contest/accept
(`policy/` already decided that before this is ever called), never computes
money beyond quoting the given `amount`.
"""

from dataclasses import dataclass

from disputedesk.evidence.context import DisputeContext
from disputedesk.evidence.llm import LLMClient
from disputedesk.evidence.prompts import load_prompt
from disputedesk.evidence.schemas import ExplanationLetterOutput, NormalizedCommunicationLog
from disputedesk.evidence.validated_call import call_llm_and_validate


@dataclass(frozen=True)
class LetterResult:
    letter: ExplanationLetterOutput
    human_review_required: bool


def _deterministic_fallback(
    context: DisputeContext, evidence_types: tuple[str, ...]
) -> ExplanationLetterOutput:
    """No LLM call. States only the raw order-context facts, with no
    narrative framing - a person reviews and improves it later
    (`human_review_required` on the result flags that).
    """
    sentences = [
        f"This letter responds to a chargeback filed under reason code {context.reason_code} "
        f"for a transaction of INR {context.amount:.2f}.",
        f"Address Verification Service match: {'yes' if context.avs_match else 'no'}.",
        f"Card Verification Value match: {'yes' if context.cvv_match else 'no'}.",
        "Device recognized from this customer's prior activity: "
        f"{'yes' if context.device_fingerprint_known else 'no'}.",
        f"Delivery or fulfillment of this transaction: "
        f"{'confirmed' if context.delivery_confirmed else 'not confirmed'}.",
        f"This customer has {context.prior_order_count} prior order(s) on this account.",
        "This letter was generated by a deterministic template because "
        "automated drafting was unavailable; it has not been reviewed by a person yet.",
    ]
    return ExplanationLetterOutput(
        letter_text=" ".join(sentences),
        cites_evidence_types=list(evidence_types),
    )


def draft_explanation_letter(
    context: DisputeContext,
    evidence_types: tuple[str, ...],
    normalized_comms: NormalizedCommunicationLog,
    llm_client: LLMClient,
) -> LetterResult:
    prompt = load_prompt("explanation_letter_v1").format(
        reason_code=context.reason_code,
        amount=f"{context.amount:.2f}",
        avs_match=context.avs_match,
        cvv_match=context.cvv_match,
        device_fingerprint_known=context.device_fingerprint_known,
        delivery_confirmed=context.delivery_confirmed,
        prior_order_count=context.prior_order_count,
        evidence_types=", ".join(evidence_types),
        comms_summary=normalized_comms.summary,
        comms_tone=normalized_comms.tone,
    )
    parsed = call_llm_and_validate(llm_client, prompt, ExplanationLetterOutput)
    if parsed is not None:
        return LetterResult(letter=parsed, human_review_required=False)

    fallback = _deterministic_fallback(context, evidence_types)
    return LetterResult(letter=fallback, human_review_required=True)
